           readers:
           - class: PolledSerialReader
             kwargs:
                port: /dev/ttyUSB4
                timeout: 1
                eol: \r
#               start_cmd: - __PAUSE__ 10
                pre_read_cmd: 
                   pause:  # not prompts, so expect this to timeout
                     - __PAUSE__ 9
                   pr0:
#                    - __PAUSE__ 10
                     - \r\nPR0\r\n
                   sr0: 
                     - \r\nSR0\r\n
                   3rd: 
                     - $3RD\r
                stop_cmd: 
                  - __PAUSE__ 10
           transforms:
           - class: StripTransform
             kwargs:               
               unprintable: true   
           - class: PrefixTransform
             kwargs:
               prefix: "WXTS"
           - class: TimestampTransform
             kwargs:
               time_format: "%Y/%m/%d %H:%M:%S.%f"
           - class: PrefixTransform
             kwargs:
               prefix: "MET"
           - class: RegexReplaceTransform
             kwargs:
               patterns: 
                 WXTS PR0: WXTP PR0
                 WXTS \*\+: FLR *+
#                MET \*\+: SSW \*\+
           writers:
           - class: UDPWriter
             kwargs:
               port: 57304
               destination: 10.100.128.22
           - class: TextFileWriter
             kwargs:
                filename: /home/admin_paul.mena/logs/serial_485_all.log
                truncate: True
