readers:
- class: SerialReader
  kwargs:
    port: /dev/ttyUSB1
    baudrate: 4800
#   eol: \r
transforms:
- class: PrefixTransform
  kwargs:
    prefix: GYRO
- class: TimestampTransform
  kwargs:
    time_format: '%Y-%m-%dT%H:%M:%S.%fZ'
- class: RegexReplaceTransform
  kwargs:
    patterns:
      '(\.\d{3})\d{3}Z': '\1Z'
- class: PrefixTransform
  kwargs:
    prefix: NAV
writers:
- class: UDPWriter
  kwargs:
    port: 57301
- class: UDPWriter
  kwargs:
    port: 57301
    destination: 10.100.161.10
- class: FileWriter
  kwargs:
    filename: /home/sssg/openrvdas_support/logs/at
#   split_by_time: True
    split_interval: 1H
    time_format: '%Y%m%d_%H00.HDT'
