           readers:
           - class: SerialReader
             kwargs:
                port: /dev/ttyUSB2
                baudrate: 9600
           transforms:
           - class: StripTransform
             kwargs:               
             unprintable: True
#            strip_prefix: True
#            chars: '\r\n'
           - class: PrefixTransform
             kwargs:
               prefix: "SBE48"
           - class: TimestampTransform
             kwargs:
               time_format: "%Y/%m/%d %H:%M:%S.%f"
           - class: PrefixTransform
             kwargs:
               prefix: "SSW"
           writers:
           - class: UDPWriter
             kwargs:
               port: 57302
               destination: 10.100.128.22
           - class: TextFileWriter
             kwargs:
                filename: /home/admin_paul.mena/logs/serial_SBE48.log
                truncate: True
