           readers:
           - class: SerialReader
             kwargs:
                port: /dev/ttyUSB3
                baudrate: 9600
#               eol: \r
           transforms:
           - class: PrefixTransform
             kwargs:
               prefix: SBE45
           - class: TimestampTransform
             kwargs:
               time_format: '%Y/%m/%d %H:%M:%S.%f'
           - class: PrefixTransform
             kwargs:
               prefix: SSW
           writers:
           - class: UDPWriter
             kwargs:
               port: 57303
               destination: 10.100.161.10
           - class: FileWriter
             kwargs:
                filename: /home/sssg/openrvdas_support/logs/at
                split_by_time: True
                split_interval: 1H
                time_format: '%Y%m%d_%H00.SBE45'
