#!/usr/bin/python

##### samos_postcsv_edit.py <arg>
##### syntax: samos_postcsv_edit.py directory 
#####	ie. renamesamos.py /home/sssg/ar44/data
##### this script reformats the files generated by dsLogPostCSV to 
##### remove the unwanted characters in the YMD and HMS and rename the files
##### to the expected daily format (i.e. WARL_SAMOS_yymmdd.csv)
##### this was req'd for dsLogPostCSV rev 124
#####
##### data goes from YMD:2020/06/09, HMS:00:01:00 to YMD: 20200609, HMS:000100
#####
##### 20200611 		cts

import os
import sys

directory = sys.argv[1]
os.chdir(directory)
newfiles = os.listdir()
samosfiles = []
for f in newfiles:
	if "samos" in f: 
		if os.path.isfile(f):
			samosfiles.append(f)
print(samosfiles)

for fname in samosfiles:
	fin = open(fname)			#samos_yyyymmdd_hhmm.csv is standard format from dsLogPostCSV
	outname = "WARL_SAMOS_"+fname[8:14]		#renames to WARL_SAMOS_yymmdd.csv
	fout = open(outname,'w')
	
	file = fin.readlines()

	for i in range(len(file)):
		if file[i].startswith("$SAMOS"):
			text = file[i]
			mod = text.split(',')
			mod[2] = mod[2].replace('/','')
			mod[3] = ' HMS:' + mod[3][5:].replace(':','')

			fout.write(','.join(mod))


	fin.close()
	fout.close()

	print(outname)

