readers:
  - class: PolledSerialReader
    kwargs:
      port: /dev/ttyUSB4
      eol: \r
      pre_read_cmd:
        pr0:
          - __PAUSE__ 10
          - PR0\r\n
        sr0:
          - SR0\r\n
        3rd:
          - $3RD\r
      stop_cmd: __PAUSE__ 10

transforms:
  - class: PrefixTransform
    kwargs:
      prefix: WXTS
  - class: TimestampTransform
    kwargs:
      time_format: '%Y/%m/%d %H:%M:%S.%f'
  - class: PrefixTransform
    kwargs:
      prefix: MET
  - class: RegexReplaceTransform
    kwargs:
      patterns:
        WXTS PR0: WXTP PR0
        '(\n)+': ''  # Remove extra newlines between header and data
        '(\r)+': ''  # Normalize carriage returns if needed

writers:
  # Port Vaisala 
  - class: TextFileWriter
    kwargs:
      filename: /home/admin_paul.mena/logs/port_vaisala.log
      truncate: True
  - class: UDPWriter
    kwargs:
      port: 57304
      destination: 10.100.100.30

  # Starboard Vaisala 
  - class: TextFileWriter
    kwargs:
      filename: /home/admin_paul.mena/logs/starboard_vaisala.log
      truncate: True
  - class: UDPWriter
    kwargs:
      port: 57404
      destination: 10.100.100.30

  # Fluorometer 
  - class: TextFileWriter
    kwargs:
      filename: /home/admin_paul.mena/logs/fluorometer.log
      truncate: True
  - class: UDPWriter
    kwargs:
      port: 57504
      destination: 10.100.100.30
