           readers:
           - class: PolledSerialReader
             kwargs:
                port: /dev/ttyUSB4
#               start_cmd:
#                 - __PAUSE__ 10
                pre_read_cmd: 
                  - PR0\r\n
                  - __PAUSE__ 2
                  - SR0\r\n
                  - __PAUSE__ 10
#                 - $3RD\r
#               stop_cmd:
#                 - __PAUSE__ 1
           writers:
           - class: UDPWriter
             kwargs:
               port: 57304
               destination: 10.100.100.30
           - class: TextFileWriter
             kwargs:
                filename: /home/admin_paul.mena/logs/vaisalas_both.log
                truncate: True
